// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRo5V11u6qI0EzGZAusAmykpBff5t5BKU',
    appId: '1:633994818909:web:474641654301e498d7a4b4',
    messagingSenderId: '633994818909',
    projectId: 'coinvert-b1b8f',
    authDomain: 'coinvert-b1b8f.firebaseapp.com',
    storageBucket: 'coinvert-b1b8f.firebasestorage.app',
    measurementId: 'G-MX7DG59Q7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdtR1Y2ZO2f5XrVC4061k7UIAfoAkbnOY',
    appId: '1:633994818909:android:1af5dccc44accef3d7a4b4',
    messagingSenderId: '633994818909',
    projectId: 'coinvert-b1b8f',
    storageBucket: 'coinvert-b1b8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxdo3Dl3rRLhMS2G9EWRkA3ynzkFbGqOA',
    appId: '1:633994818909:ios:39566aa6b3ef8a97d7a4b4',
    messagingSenderId: '633994818909',
    projectId: 'coinvert-b1b8f',
    storageBucket: 'coinvert-b1b8f.firebasestorage.app',
    iosBundleId: 'com.example.coinvertKiosk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxdo3Dl3rRLhMS2G9EWRkA3ynzkFbGqOA',
    appId: '1:633994818909:ios:39566aa6b3ef8a97d7a4b4',
    messagingSenderId: '633994818909',
    projectId: 'coinvert-b1b8f',
    storageBucket: 'coinvert-b1b8f.firebasestorage.app',
    iosBundleId: 'com.example.coinvertKiosk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRo5V11u6qI0EzGZAusAmykpBff5t5BKU',
    appId: '1:633994818909:web:474641654301e498d7a4b4',
    messagingSenderId: '633994818909',
    projectId: 'coinvert-b1b8f',
    authDomain: 'coinvert-b1b8f.firebaseapp.com',
    storageBucket: 'coinvert-b1b8f.firebasestorage.app',
    measurementId: 'G-MX7DG59Q7D',
  );
}
