import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter/foundation.dart' show kDebugMode;
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';

import 'firebase_options.dart'; // generated by `flutterfire configure`

import 'theme/colors.dart';
import 'services/serial_service.dart';
import 'services/ai_auth_service.dart';
import 'services/firebase_service.dart';
import 'state/kiosk_controller.dart';
import 'widgets/kiosk_frame.dart';
import 'widgets/error_overlay.dart';
import 'widgets/sim_debug_panel.dart';

/// Must match an existing `kiosks/{kioskId}` document that was created via
/// the admin app's Kiosk Pairing screen (e.g. 'kiosk-01', 'kiosk-02') —
/// this is NOT a free-form ID, it's a foreign key into that collection.
const String kKioskId = 'kiosk-01';

/// Flip to false once you're actually running on the Pi with the Arduino
/// and the Python AI service wired up. While true, SerialService and
/// AiAuthService never touch real hardware/HTTP — you drive the whole
/// flow (insert cash, authenticate, dispense) from the on-screen debug
/// panel instead. Firebase is still REAL either way (it's the one part
/// of this stack you don't need a Pi to test against).
const bool kSimulateHardware = true;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  SystemChrome.setPreferredOrientations([
    DeviceOrientation.landscapeLeft,
    DeviceOrientation.landscapeRight,
  ]);
  SystemChrome.setEnabledSystemUIMode(SystemUiMode.immersiveSticky);

  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    debugPrint('Firebase not configured yet: $e');
  }

  final serial = SerialService(simulate: kSimulateHardware);
  final aiAuth = AiAuthService(simulate: kSimulateHardware);
  final firebase = FirebaseService(kioskId: kKioskId);

  final controller = KioskController(
    serial: serial,
    aiAuth: aiAuth,
    firebase: firebase,
  );
  await controller.initialize();

  runApp(CoinvertKioskApp(
    controller: controller,
    serial: serial,
    aiAuth: aiAuth,
  ));
}

class CoinvertKioskApp extends StatelessWidget {
  final KioskController controller;
  final SerialService serial;
  final AiAuthService aiAuth;

  const CoinvertKioskApp({
    super.key,
    required this.controller,
    required this.serial,
    required this.aiAuth,
  });

  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider<KioskController>.value(
      value: controller,
      child: MaterialApp(
        title: 'Coinvert Kiosk',
        debugShowCheckedModeBanner: false,
        theme: ThemeData(
          useMaterial3: true,
          fontFamily: 'Roboto',
          scaffoldBackgroundColor: const Color(0xFFF3F5F1),
          colorScheme: ColorScheme.fromSeed(seedColor: AppColors.green),
        ),
        home: KioskScreen(serial: serial, aiAuth: aiAuth),
      ),
    );
  }
}

class KioskScreen extends StatelessWidget {
  final SerialService serial;
  final AiAuthService aiAuth;
  const KioskScreen({super.key, required this.serial, required this.aiAuth});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF3F5F1),
      body: SafeArea(
        child: Center(
          child: Padding(
            padding: const EdgeInsets.all(24),
            child: AspectRatio(
              aspectRatio: 620 / 372,
              child: Stack(
                children: [
                  const KioskFrame(),
                  const ErrorOverlay(),
                  if (kSimulateHardware && kDebugMode)
                    SimDebugPanel(serial: serial, aiAuth: aiAuth),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
